# Generated by Django 4.2.7 on 2025-03-13 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engagement', '0001_initial'),
        ('parliament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whistleblowing',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_whistleblowing_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='whistleblowing',
            name='related_mp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whistleblowing_reports', to='parliament.mp'),
        ),
        migrations.AddField(
            model_name='whistleblowing',
            name='related_party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whistleblowing_reports', to='parliament.politicalparty'),
        ),
        migrations.AddField(
            model_name='whistleblowing',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whistleblowing_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_threads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussionthread',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='engagement.discussionforum'),
        ),
        migrations.AddField(
            model_name='discussionpost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussionpost',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='engagement.discussionthread'),
        ),
        migrations.AddField(
            model_name='discussionforum',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderated_forums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='discussionforum',
            name='related_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_forums', to='parliament.bill'),
        ),
        migrations.AddField(
            model_name='discussionforum',
            name='related_mp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_forums', to='parliament.mp'),
        ),
        migrations.AddField(
            model_name='discussionforum',
            name='related_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussion_forums', to='parliament.topic'),
        ),
        migrations.AlterUniqueTogether(
            name='discussionthread',
            unique_together={('forum', 'slug')},
        ),
    ]
