# Generated by Django 4.2.27 on 2025-12-23 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussionthread',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
