# Generated by Django 4.2.7 on 2026-01-08 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0009_add_fyrirspurn_status_choices'),
        ('engagement', '0003_alter_discussionthread_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionthread',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='discussion_threads', to='parliament.topic'),
        ),
        migrations.AlterField(
            model_name='discussionthread',
            name='forum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='threads', to='engagement.discussionforum'),
        ),
    ]
