# Generated by Django 4.2.27 on 2026-01-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0004_discussionthread_topics_alter_discussionthread_forum'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionpost',
            name='downvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discussionpost',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discussionpost',
            name='user_votes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
