# Generated by Django 4.2.27 on 2026-01-08 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0005_discussionpost_downvotes_discussionpost_upvotes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussionpost',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='engagement.discussionpost'),
        ),
    ]
