# Generated by Django 4.2.7 on 2025-03-10 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('althingi_id', models.IntegerField(help_text='Bill ID from the Alþingi database', unique=True)),
                ('description', models.TextField()),
                ('full_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('introduced', 'Introduced'), ('in_committee', 'In Committee'), ('in_debate', 'In Debate'), ('amended', 'Amended'), ('passed', 'Passed'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='introduced', max_length=20)),
                ('introduced_date', models.DateField()),
                ('url', models.URLField(help_text='Link to bill on Alþingi website')),
                ('committee_referral_date', models.DateField(blank=True, null=True)),
                ('debate_date', models.DateField(blank=True, null=True)),
                ('vote_date', models.DateField(blank=True, null=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-introduced_date'],
            },
        ),
        migrations.CreateModel(
            name='MP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('althingi_id', models.IntegerField(help_text='MP ID from the Alþingi database', unique=True)),
                ('constituency', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='mp_photos/')),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('social_media_links', models.JSONField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('first_elected', models.DateField(blank=True, null=True)),
                ('current_position_started', models.DateField(blank=True, null=True)),
                ('end_of_service', models.DateField(blank=True, null=True)),
                ('speech_count', models.IntegerField(default=0)),
                ('bills_sponsored', models.IntegerField(default=0)),
                ('bills_cosponsored', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'MP',
                'verbose_name_plural': 'MPs',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ParliamentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_number', models.IntegerField(help_text='Number of the parliamentary session')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-session_number'],
            },
        ),
        migrations.CreateModel(
            name='PoliticalParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='party_logos/')),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('founding_date', models.DateField(blank=True, null=True)),
                ('color', models.CharField(blank=True, help_text='Party color in hex format (e.g., #FF0000)', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Political parties',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('duration', models.IntegerField(blank=True, help_text='Duration in seconds', null=True)),
                ('video_url', models.URLField(blank=True)),
                ('transcript_url', models.URLField(blank=True)),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, null=True)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='parliament.bill')),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='parliament.mp')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches', to='parliament.parliamentsession')),
            ],
            options={
                'verbose_name_plural': 'Speeches',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='mp',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='members', to='parliament.politicalparty'),
        ),
        migrations.AddField(
            model_name='bill',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='parliament.parliamentsession'),
        ),
        migrations.AddField(
            model_name='bill',
            name='sponsors',
            field=models.ManyToManyField(related_name='sponsored_bills', to='parliament.mp'),
        ),
        migrations.AddField(
            model_name='bill',
            name='topics',
            field=models.ManyToManyField(related_name='bills', to='parliament.topic'),
        ),
        migrations.CreateModel(
            name='Amendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('date_proposed', models.DateField()),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('adopted', 'Adopted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='proposed', max_length=20)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='parliament.bill')),
                ('proposed_by', models.ManyToManyField(related_name='proposed_amendments', to='parliament.mp')),
            ],
            options={
                'ordering': ['-date_proposed'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('abstain', 'Abstain'), ('absent', 'Absent')], max_length=10)),
                ('vote_date', models.DateField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='parliament.bill')),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_record', to='parliament.mp')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='parliament.parliamentsession')),
            ],
            options={
                'ordering': ['-vote_date'],
                'unique_together': {('bill', 'mp')},
            },
        ),
    ]
