# Generated by Django 4.2.7 on 2025-03-13 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='cosponsors',
            field=models.ManyToManyField(blank=True, related_name='cosponsored_bills', to='parliament.mp'),
        ),
        migrations.AddField(
            model_name='bill',
            name='primary_sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsored_bills', to='parliament.mp'),
        ),
    ]
