# Generated by Django 5.0.4 on 2025-03-10 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0002_alter_mp_party'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('session', 'slug')},
        ),
        migrations.AlterField(
            model_name='bill',
            name='althingi_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bill',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='slug',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bill',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='bill',
            name='url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.RemoveField(
            model_name='bill',
            name='committee_referral_date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='debate_date',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='full_text',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='last_update',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='sponsors',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='vote_date',
        ),
    ]
