# Generated by Django 5.1.7 on 2025-03-13 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0002_bill_cosponsors_bill_primary_sponsor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MPInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('board_positions', models.TextField(blank=True, help_text='Paid board memberships in private or public companies')),
                ('paid_work', models.TextField(blank=True, help_text='Paid work or projects (other than MP duties)')),
                ('business_activities', models.TextField(blank=True, help_text='Business activities conducted alongside parliamentary work')),
                ('financial_support', models.TextField(blank=True, help_text='Financial support or contributions from domestic and foreign entities')),
                ('gifts', models.TextField(blank=True, help_text='Gifts valued over 50,000 ISK and likely provided due to MP position')),
                ('trips', models.TextField(blank=True, help_text='Domestic and foreign trips related to parliamentary duties')),
                ('debt_forgiveness', models.TextField(blank=True, help_text='Debt forgiveness and favorable changes to loan terms')),
                ('real_estate', models.TextField(blank=True, help_text='Real estate ownership (excluding personal residence)')),
                ('company_ownership', models.TextField(blank=True, help_text='Companies, savings banks, or self-owned institutions in which the MP owns shares')),
                ('former_employer_agreements', models.TextField(blank=True, help_text='Financial agreements with former employers')),
                ('future_employer_agreements', models.TextField(blank=True, help_text='Employment agreements with future employers')),
                ('other_positions', models.TextField(blank=True, help_text='Board memberships and other positions of trust for interest groups')),
                ('source_url', models.URLField(blank=True, help_text='URL to the interests declaration on the Althingi website')),
                ('mp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='parliament.mp')),
            ],
            options={
                'verbose_name': "MP's Interest Declaration",
                'verbose_name_plural': 'MP Interest Declarations',
            },
        ),
    ]
