# Generated by Django 5.1.7 on 2025-03-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0003_mpinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp',
            name='total_speaking_time',
            field=models.IntegerField(default=0, help_text='Total speaking time in seconds'),
        ),
    ]
