# Generated by Django 5.0.4 on 2025-03-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0003_alter_bill_unique_together_alter_bill_althingi_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='keywords',
            field=models.JSONField(blank=True, default=list, help_text='List of keywords used to identify this topic'),
        ),
    ]
