# Generated by Django 5.1.7 on 2025-03-13 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0004_mp_total_speaking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('introduced', 'Introduced'), ('in_committee', 'In Committee'), ('in_debate', 'In Debate'), ('passed', 'Passed'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='introduced', max_length=20),
        ),
        migrations.AlterField(
            model_name='bill',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='bills', to='parliament.topic'),
        ),
    ]
