# Generated by Django 5.0.4 on 2025-03-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0004_topic_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicalparty',
            name='althingi_id',
            field=models.CharField(blank=True, help_text='Party ID from the Alþingi database', max_length=20, null=True, unique=True),
        ),
    ]
