# Generated by Django 5.1.7 on 2025-03-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0005_alter_bill_status_alter_bill_topics'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bill',
            unique_together={('althingi_id', 'session')},
        ),
        migrations.AddField(
            model_name='bill',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='sponsors',
            field=models.ManyToManyField(blank=True, related_name='sponsored_bills', to='parliament.mp'),
        ),
        migrations.AddField(
            model_name='bill',
            name='vote_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bill',
            name='url',
            field=models.URLField(max_length=500),
        ),
        migrations.RemoveField(
            model_name='bill',
            name='primary_sponsor',
        ),
    ]
