# Generated by Django 4.2.7 on 2025-03-11 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0006_remove_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='mp',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mps', to='parliament.politicalparty'),
        ),
        migrations.AlterField(
            model_name='mp',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
