# Generated by Django 5.1.7 on 2025-03-13 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0006_alter_bill_unique_together_bill_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='althingi_voting_id',
            field=models.CharField(blank=True, help_text='Voting session ID from Alþingi (nnafnak)', max_length=20, null=True),
        ),
    ]
