# Generated by Django 4.2.7 on 2025-03-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0007_alter_mp_email_alter_mp_party_alter_mp_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='mp',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
    ]
