# Generated by Django 4.2.7 on 2026-01-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0007_vote_althingi_voting_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(blank=True, choices=[('frumvarp', 'Frumvörp'), ('thingsalyktun', 'Þingsályktunartillögur'), ('fyrirspurn', 'Fyrirspurnir')], default='frumvarp', max_length=20),
        ),
        migrations.AddField(
            model_name='bill',
            name='submitter_type',
            field=models.CharField(blank=True, choices=[('government', 'Stjórnarfrumvörp'), ('member', 'Þingmannafrumvörp'), ('committee', 'Nefndafrumvörp')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('awaiting_first_reading', 'Bíða 1. umræðu'), ('in_committee', 'Í nefnd'), ('awaiting_second_reading', 'Bíða 2. umræðu'), ('awaiting_third_reading', 'Bíða 3. umræðu'), ('passed', 'Samþykkt'), ('rejected', 'Fellt'), ('withdrawn', 'Dregið til baka')], default='awaiting_first_reading', max_length=30),
        ),
    ]
