# Generated by Django 4.2.7 on 2025-03-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0008_mp_facebook_url_mp_twitter_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='mp_images/'),
        ),
        migrations.AlterField(
            model_name='mp',
            name='constituency',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mp',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
