# Generated by Django 4.2.7 on 2026-01-08 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0008_bill_bill_type_bill_submitter_type_alter_bill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('awaiting_first_reading', 'Bíða 1. umræðu'), ('in_committee', 'Í nefnd'), ('awaiting_second_reading', 'Bíða 2. umræðu'), ('awaiting_third_reading', 'Bíða 3. umræðu'), ('passed', 'Samþykkt'), ('rejected', 'Fellt'), ('withdrawn', 'Dregið til baka'), ('question_sent', 'Fyrirspurn send'), ('question_answered', 'Fyrirspurn svarað')], default='awaiting_first_reading', max_length=30),
        ),
    ]
