# Generated by Django 4.2.7 on 2025-03-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0009_mp_image_alter_mp_constituency_alter_mp_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mp',
            name='image',
        ),
        migrations.AddField(
            model_name='mp',
            name='image_url',
            field=models.URLField(blank=True, help_text="URL to MP's image on Althingi website"),
        ),
    ]
