# Generated by Django 4.2.7 on 2025-03-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0010_remove_mp_image_mp_image_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='speech',
            options={'ordering': ['-date', '-start_time'], 'verbose_name_plural': 'Speeches'},
        ),
        migrations.AddField(
            model_name='speech',
            name='althingi_bill_id',
            field=models.IntegerField(blank=True, help_text='Bill number in Alþingi', null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='audio_url',
            field=models.URLField(blank=True, help_text='URL to audio recording'),
        ),
        migrations.AddField(
            model_name='speech',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='html_url',
            field=models.URLField(blank=True, help_text='URL to HTML version'),
        ),
        migrations.AddField(
            model_name='speech',
            name='speech_type',
            field=models.CharField(blank=True, help_text='Type of speech (e.g., ræða, andsvar)', max_length=50),
        ),
        migrations.AddField(
            model_name='speech',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='speech',
            name='xml_url',
            field=models.URLField(blank=True, help_text='URL to XML version'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='speech',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='speech',
            name='transcript_url',
            field=models.URLField(blank=True, help_text='URL to transcript'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL to video recording'),
        ),
    ]
