# Generated by Django 4.2.7 on 2025-03-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parliament', '0011_alter_speech_options_speech_althingi_bill_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='speech',
            name='mp_althingi_id',
            field=models.IntegerField(blank=True, help_text='MP ID from the Alþingi database', null=True),
        ),
    ]
